config/routes.rb
Demo2::Application.routes.draw do
  resources :recipes

  get "store" => "stores#index", :as => 'store'
  get "store/:id(.:format)" => "stores#show", :as => 'store_id'

  get "page/login"
  get "page/blog"
  get "page/home"
  get "page/about_us"
  post "page/about_us"
  get "page/product"
  get "page/articles"
  get "page/calendar"
  get "say/hello"

  root 'recipes#index'

  

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

validates_presence_of :name, :ingredients, :made_by 
validates_numericality_of :serves, :only_integer => true 
validates_uniqueness_of :name 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   layout "application"
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about_us
    @name = params[:name]
    @email = params[:email ]
    @age = params[:age]
    @food = params[:food]
    
    if params[:commit] 
      flash.now[:error] = ' '
      if @name.nil? || @name.empty?
        flash.now[:error] << "Name cannot be blank. <br/>"
      end
      if @email.nil? || @email.empty?
        flash.now[:error] << "Email cannot be blank. <br/>"
      end
    end
  end

  def recipes
    @recipes = Recipe.all 

  end

  def product
  end

  def articles
  end

  def calendar
    @year = params[:year]
    @month = params[:month]
    @name = 'Marty Lavin'
    @My_time = Time.now
    @products = %w(skis boots mittens poles coats pants gloves)

  end

  def blog
  end

  def login
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  # before_filter :authenticate

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
    username == "foo" && password == "bar"
    end
  end

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :serves, :cost, :made_by, :last_made, :ingredients, :image)
    end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @recipes = Recipe.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /stores/1
  # GET /stores/1.json
  #def show
  #  @store = Recipe.find(params[:id])
  #end
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:index, :show)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def calendar(month, year)
		prev_month = link_to "previous", page_calendar_path(:month =>month.to_i - 1)
		cal_string = "<table border = '1'>"
		cal_string += "<tr><td>#{prev_month}</td><td colspan=7>October</td></tr>"
		cal_string += "<tr>"
		cal_string += "<td>&nbsp;</td>"

		6.times do | day |
			cal_string += "<td> #{day+1}</td>"
		end

		cal_string += "</tr>"
		cal_string += "</table>"
		return cal_string.html_safe
	end
#______________________________________________________________

	def things_to_do(links)
		# key = url, value = body
		html = "<ul>"
		links.each do |url, body|
			html += "<li>" + link_to( body, url) + "</li>"
		end 

		html += "</ul>"
		return html.html_safe		
	end

def show_params
	#html = '<div style = 'border: 2px red solid'>' 
	#html += '<heading>Params<heading/>'
	html += params.each do |key, value|
	html += "#{key}: #{value} <BR />"	
	end
	#html += '</div>'
	return html.html_safe
end

def puts_test
		html1 = "<h1>Ask a supid marty 333question</h1>"
		"jjjjjj"
		return html1.html_safe
	end

	
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/_navigation.html.erb
<div class="menu">
	<ul>
		<li><%=link_to_unless_current "Home", page_home_path %></li>
		<li><%=link_to_unless_current "About us", page_about_us_path %></li>
		<li><%=link_to_unless_current "Recipes", store_path %></li>
		<li><%=link_to_unless_current "Articles", page_articles_path %></li>
		<li><%=link_to_unless_current "Calendar", page_calendar_path %></li>
		<li><%=link_to_unless_current "Blog", page_blog_path %></li>
		<li><%=link_to_unless_current "Log in", page_login_path %></li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Marty's Recipes: <%= yield :title %></title>
  <meta charset="utf-8" />
  <!--<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %> -->
   <%= stylesheet_link_tag    "application", media: "screen", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "print", media: "print", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
<div id="wrapper"><!-- #wrapper -->


	<nav><!-- top nav -->
		<%=render :partial => 'layouts/navigation' %>
	</nav><!-- end of top nav -->
	
<header><!-- header -->
		<div id="headerlogo"><img <%= image_tag("Marty_Lavin.jpg", :size => "120x120", :mouseover => image_path("rails.png")) %></div>
		<h1><a href="#">Marty's Best Recipes</a></h1>
		<h2>Isn't he cute?</h2>
	</header><!-- end of header -->



<section id="main"><!-- #main content and sidebar area -->
			<section id="content"><!-- #content -->

				<div styles = "border: 2px solid.red"
					<% if flash[:notice] %>
					<p class= "notice"><%= flash[:notice].html_safe %></p>
					<%end%>
					<% if flash[:error] %>
					<p class= "error"><%= flash[:error].html_safe %></p>
					<%end%>	
				</div>			

<%= yield %>

			</section><!-- end of #content -->

	<aside id="sidebar"><!-- sidebar -->
				<h3>Things To Do</h3>
					<%= things_to_do('http://www.google.com'  => 'www.google.com',
						'http://www.lmgtfy.com' => 'www.lmgtfy.com',
						page_calendar_path => 'Events') %>

					
				<h3>Sponsors</h3>
					<%= image_tag "ad125.jpg" %><br /><%= image_tag "ad125.jpg" %><br /><br />

				<h3>Connect With Us</h3>
					<ul>
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Facebook</a></li>
					</ul>

		</aside><!-- end of sidebar -->

	</section><!-- end of #main content and sidebar-->
<footer>
		<section id="footer-area">

			<section id="footer-outer-block">
					<aside class="footer-segment">
							<h4>Friends</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #first footer segment -->

					<aside class="footer-segment">
							<h4>Awesome Stuff</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #second footer segment -->

					<aside class="footer-segment">
							<h4>Coolness</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #third footer segment -->
					
					<aside class="footer-segment">
							<h4>Blahdyblah</h4>
								<p>&copy; 2010 <a href="#">yoursite.com</a> Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. </p>
					</aside><!-- end of #fourth footer segment -->

			</section><!-- end of footer-outer-block -->

		</section><!-- end of footer-area -->
	</footer>
	
</div><!-- #wrapper -->
<!-- Free template created by http://freehtml5templates.com -->
</body>
</html>

app/views/page/about_us.html.erb
<h1>Page#about_us</h1>

<%= content_for :title do %>
	About us stuff, to make sure seo, important ranking stuff.
<% end %>
<!-- <%= flash[:error] %>-->
<%= field_set_tag "Information", :class => 'input' do %><BR />
	<%= form_tag do %>
		<%= label_tag 'Name: ' %>
		<%= text_field_tag 'name', @name, :size => 50 %><BR /><BR />
		<%= label_tag 'Email: ' %>
		<%= email_field_tag 'email', @email, :placeholder => 'Enter your email address', :size => 50 %><BR /><BR />
		<%= label_tag 'Age:   ' %>
		<%= number_field_tag 'age', @age, :min => 13,  :max => 120 %><BR /><BR />
		<h2>What would you like to bring to the potluck?</h2>
		<%= label_tag :food_salad, "Salad"  %>
		<%= radio_button_tag  :food, :salad, @food == "salad"  %><BR />
		<%= label_tag :food_main, "Main Dish"  %>
		<%= radio_button_tag  :food, :main, @food == "main"  %><BR />
		<%= label_tag :food_dessert, "Dessert"  %>
		<%= radio_button_tag  :food, :dessert, @food == "dessert"  %><BR />
		<p><%= submit_tag 'Submit your question'%><BR /></p>
	<% end %>
<% end %>
<%= params.inspect %>

<!-- <div style = "border: 2px red solid">
	<heading> Params </heading>
	<%= "Name: #{@name}" %>
	<%= "Email: #{@email}" %>
	<%= params.inspect %>
</div> -->

<!-- <%=  puts_test %> -->

app/views/page/articles.html.erb
<h1>Page#articles</h1>

<%= content_for :title do %>
	Articles for the seo, important ranking stuff.
<% end %>



<p>Find me in app/views/page/articles.html.erb</p>

app/views/page/blog.html.erb
<h1>Page#blog</h1>
<p>Find me in app/views/page/blog.html.erb</p>

app/views/page/calendar.html.erb
<h1>Page#calendar for Marty</h1>
<p>Find me in app/views/page/calender.html.erb</p>

<%= @name + ' ' + @my_time.to_s%>
<p><%= @month %> <% @year %> Products <br/> </p>


<%= calendar(@month, @year) %> 

<br/>
<ol>
<% @products.each do |product| %>
<li><%= product.capitalize %></li>
<% end %>
</ol>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/page/login.html.erb
<h1>Page#login</h1>
<p>Find me in app/views/page/login.html.erb</p>

app/views/page/product.html.erb
<h1>Page#product</h1>
<p>Find me in app/views/page/product.html.erb</p>

app/views/page/recipes.html.erb
<h3>Page#recipes</h3>

<% @recipes.each do |recipe| %>
<section style="border: 2px solid black; padding: 10px:margin:10px">
	<h3> <%= recipe.name %> </h3> 
	Made by: <%= recipe.made_by%><br/>
	Serves: <%= recipe.serves %><br/>
	Last Made: <%= recipe.last_made %>
</section>
<% end %>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :serves %><br>
    <%= f.number_field :serves %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :made_by %><br>
    <%= f.text_field :made_by %>
  </div>
  <div class="field">
    <%= f.label :last_made %><br>
    <%= f.datetime_select :last_made, :start_year => 2000 %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<%= will_paginate @recipes %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Serves</th>
      <th>Cost</th>
      <th>Made by</th>
      <th>Last made</th>
      <th>Ingredients</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.name, recipe %></td>
        <td><%= recipe.serves %></td>
        <td><%= number_to_currency(recipe.cost) %></td>
        <td><%= recipe.made_by %></td>
        <td><%= recipe.last_made %></td>
        <td><%= truncate (recipe.ingredients).html_safe %></td>
        <td><%= link_to "My Image", "/assets/#{recipe.image}" %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <%= will_paginate @recipes, :class=>'apple_pagination' %>

<br />
<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Serves:</strong>
  <%= @recipe.serves %>
</p>

<p>
  <strong>Cost:</strong>
  <%= number_to_currency(@recipe.cost)%>
</p>

<p>
  <strong>Made by:</strong>
  <%= @recipe.made_by %>
</p>

<p>
  <strong>Last made:</strong>
  <%= @recipe.last_made %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients.html_safe %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @recipe.image %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/say/hello.html.erb
<h1>Say#hello</h1>

<h1>Hi marty lavin</h1>

ahh you are the man

<p>Find me in app/views/say/hello.html.erb</p>

app/views/stores/index.html.erb
<h1>Listing recipes</h1>

<%= will_paginate @recipes %><br />
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ingredients</th>
      <th>Image</th>
      <th>Cost</th>
       <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.name, store_id_path(recipe.id) %></td>
        <td><%= truncate (recipe.ingredients).html_safe %></td>
        <td><%= link_to "My Image", "/assets/#{recipe.image}" %></td>
        <td><%= number_to_currency(recipe.cost) %></td>
        <td><%= link_to 'Show', store_id_path(recipe.id)  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <%= will_paginate @recipes, :class=>'apple_pagination' %>

<br />
<!--<%= link_to 'New Recipe', new_recipe_path %>-->

app/views/stores/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Serves:</strong>
  <%= @recipe.serves %>
</p>

<p>
  <strong>Cost:</strong>
  <%= number_to_currency(@recipe.cost)%>
</p>

<p>
  <strong>Made by:</strong>
  <%= @recipe.made_by %>
</p>

<p>
  <strong>Last made:</strong>
  <%= @recipe.last_made %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients.html_safe %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @recipe.image %>
</p>

<%= link_to 'Back', store_path %>